before:
  hooks:

builds:
  - main: ./cmd/aserto-idp-sync
    binary: aserto-idp-sync
    tags: []
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto-idp-sync/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/aserto-idp-sync/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto-idp-sync/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: zip
    builds:
    - aserto-idp-sync
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - README.md
    name_template: "aserto-idp-sync{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: aserto-dev
    name: aserto-idp-sync

  draft: false
  prerelease: false
  name_template: "aserto-idp-sync {{.Tag}}"

brews:
  - name: aserto-idp-sync

    tap:
      owner: aserto-dev
      name: aserto-idp-sync
      token: "{{ .Env.ASERTO_TAP }}"

    url_template: "https://github.com/aserto-dev/aserto-idp-sync/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "lib/custom_download_strategy"

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://aserto.com/"

    description: "Aserto IDP Sync"

    license: "apache-2"

    skip_upload: false

    test: |
      system "#{bin}/aserto-idp-sync version"
    install: |
      bin.install "aserto-idp-sync"