# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class AsertoIdpSync < Formula
  desc "Aserto IDP Sync"
  homepage "https://aserto.com/"
  version "0.0.3"
  license "apache-2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/aserto-idp-sync/releases/download/v0.0.3/aserto-idp-sync0.0.3_darwin_x86_64.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8948059e332d00226c506a4189016126cdfed313d1bf6bfbc081eda33941a386"
    end
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/aserto-idp-sync/releases/download/v0.0.3/aserto-idp-sync0.0.3_darwin_arm64.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "03335f11e303e1236b908667d34ca046e8345fa7b62264b1739d3b8230cb00c1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/aserto-idp-sync/releases/download/v0.0.3/aserto-idp-sync0.0.3_linux_x86_64.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "04708576677f5d650a1263112c4f6d57234f35f52a52b6088591d25477b9ccea"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/aserto-idp-sync/releases/download/v0.0.3/aserto-idp-sync0.0.3_linux_arm64.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d8e7e2630952c59208f8bf0ce776d1ef1253c0bcad3521722c680ba54393ca91"
    end
  end

  def install
    bin.install "aserto-idp-sync"
  end

  test do
    system "#{bin}/aserto-idp-sync version"
  end
end
