# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class AsertoIdpSync < Formula
  desc "Aserto IDP Sync"
  homepage "https://aserto.com/"
  version "0.0.2"
  license "apache-2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/aserto-idp-sync/releases/download/v0.0.2/aserto-idp-sync0.0.2_darwin_x86_64.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a0e6851d5afe0129918dcd4ea4db86b4ba00b7341471908efae9ce15c0698560"
    end
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/aserto-idp-sync/releases/download/v0.0.2/aserto-idp-sync0.0.2_darwin_arm64.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4d369935984445a1bd19b19b8bbfc937b88f3b475dd46e8ae93daf561e0e9070"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/aserto-idp-sync/releases/download/v0.0.2/aserto-idp-sync0.0.2_linux_x86_64.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dfd9b19cbc6d3fe372eb7a244e57f4a0b2de063d8c3a7a0ba9e8415f1d09509d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/aserto-idp-sync/releases/download/v0.0.2/aserto-idp-sync0.0.2_linux_arm64.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c6a5f30b8bfc7025f45bc72d227ac310f501b023f57d06d107e81a45d2d865fa"
    end
  end

  def install
    bin.install "aserto-idp-sync"
  end

  test do
    system "#{bin}/aserto-idp-sync version"
  end
end
