// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/aserto-dev/idpsync/pkg/app/impl"
	"github.com/aserto-dev/idpsync/pkg/app/server"
	"github.com/aserto-dev/idpsync/pkg/cc"
	"github.com/aserto-dev/idpsync/pkg/cc/config"
	"github.com/google/wire"
	"io"
)

// Injectors from wire.go:

func BuildIdpsync(logWriter io.Writer, configPath config.Path, overrides config.Overrider) (*App, func(), error) {
	ccCC, cleanup, err := cc.NewCC(logWriter, configPath, overrides)
	if err != nil {
		return nil, nil, err
	}
	context := ccCC.Context
	logger := ccCC.Log
	configConfig := ccCC.Config
	group := ccCC.ErrGroup
	idpSync := impl.NewIDPSync(logger, configConfig)
	registrations := GRPCServerRegistrations(idpSync)
	handlerRegistrations := GatewayServerRegistrations()
	serverServer, err := server.NewServer(context, configConfig, logger, group, registrations, handlerRegistrations)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := &App{
		Context:       context,
		Logger:        logger,
		Configuration: configConfig,
		Server:        serverServer,
	}
	return app, func() {
		cleanup()
	}, nil
}

func BuildTestIdpsync(logWriter io.Writer, configPath config.Path, overrides config.Overrider) (*App, func(), error) {
	ccCC, cleanup, err := cc.NewTestCC(logWriter, configPath, overrides)
	if err != nil {
		return nil, nil, err
	}
	context := ccCC.Context
	logger := ccCC.Log
	configConfig := ccCC.Config
	group := ccCC.ErrGroup
	idpSync := impl.NewIDPSync(logger, configConfig)
	registrations := GRPCServerRegistrations(idpSync)
	handlerRegistrations := GatewayServerRegistrations()
	serverServer, err := server.NewServer(context, configConfig, logger, group, registrations, handlerRegistrations)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := &App{
		Context:       context,
		Logger:        logger,
		Configuration: configConfig,
		Server:        serverServer,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var (
	appSet = wire.NewSet(cc.NewCC, GRPCServerRegistrations,
		GatewayServerRegistrations, server.NewServer, impl.NewIDPSync, wire.FieldsOf(new(*cc.CC), "Config", "Log", "Context", "ErrGroup"),
	)

	appTestSet = wire.NewSet(cc.NewTestCC, GRPCServerRegistrations,
		GatewayServerRegistrations, server.NewServer, impl.NewIDPSync, wire.FieldsOf(new(*cc.CC), "Config", "Log", "Context", "ErrGroup"),
	)
)
